title: Reload
subtitle: ''
description: ''
author: X.du
language: en
timezone: ''

url: https://xdu.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults: {}

theme: next

deploy:
  type: git
  repo: https://github.com/xdu/hexo-blog.git
  branch: gh-pages
