title: RELOAD.
subtitle: '发现有趣的事'
description: ''
author: X.du
language: zh
timezone: ''

url: https://xdu.github.io/
root: /hexo-blog
permalink: :year/:month/:day/:title/
permalink_defaults: {}

theme: next

deploy:
  type: git
  repo: https://github.com/xdu/hexo-blog.git
  branch: gh-pages
